baseURL = "https://dkharms.github.io/"
languageCode = "en-us"
title = "dkharms' blog"
theme = "ascii-gruvbox"

[markup]
  [markup.highlight]
    style = "catppuccin-macchiato"

    lineNos = true
    lineNumbersInTable = false

    noClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[params]
  author = "Daniil Porokhnin"

[taxonomies]
  tag = "tags"

[menu]
